export const ALLOWED_IPC_CHANNELS = [
  'db:createProject',
  'db:updateProject',
  'db:getProjects',
  'db:deleteProject',
  'db:createUser',
  'db:updateUser',
  'db:getCurrentUser',
  'db:assignProjectsToUser',
  'db:getSchedules',
  'db:saveSchedule',
  'db:deleteSchedule',
  'scheduler:runNow',
  'db:saveSpec',
  'db:getSpecsForProject',
  'db:deleteSpec',
  'db:saveEnvironment',
  'db:getEnvironmentsForProject',
  'db:deleteEnvironment',
  'db:setActiveEnvironment',
  'db:addValidationRun',
  'db:getValidationRuns',
  'db:clearValidationRuns',
  'db:deleteValidationRuns',
  'db:addValidationResult',
  'db:getValidationResult',
  'api:parseSpecContent',
  'api:pickSpecFile',
  'api:verifyOAuthToken',
  'api:prepareEnvironmentForRequests',
  'api:sendRequest',
  'api:validateResponse',
  'settings:getProxy',
  'settings:saveProxy',
  'linuxSearchAssistant:search',
  'linuxSearchAssistant:getStatus',
  'linuxSearchAssistant:setEnabled',
  'linuxSearchAssistant:getCategories',
  'linuxSearchAssistant:remoteSearch',
  'linuxSearchAssistant:sshConnect',
  'linuxSearchAssistant:sshDisconnect',
  'linuxSearchAssistant:sshIsConnected',
  'linuxSearchAssistant:sshListSessions',
  'linuxSearchAssistant:getConfig',
  'linuxSearchAssistant:saveConfig',
  'linuxSearchAssistant:listRecentActions',
  'linuxSearchAssistant:getRecentActionsPrefs',
  'linuxSearchAssistant:setRecentActionsHistorySize',
  'linuxSearchAssistant:setRecentActionPinned',
  'linuxSearchAssistant:removeRecentAction',
  'linuxSearchAssistant:clearUnpinnedRecentActions',
  'linuxSearchAssistant:executeLogicalAction',
  'linuxSearchAssistant:executeLogicalActionBatch',
  'linuxSearchAssistant:replayRecentAction',
  'linuxSearchAssistant:getDebugInfo',
  'linuxSearchAssistant:getLogTail',
  'linuxSearchAssistant:listRemoteFiles',
  'linuxSearchAssistant:getAskAiConfig',
  'linuxSearchAssistant:saveAskAiConfig',
  'linuxSearchAssistant:analyzeAskAi',
  'linuxSearchAssistant:testAskAiLlm',
  'linuxSearchAssistant:testAskAiMcp',
  'linuxSearchAssistant:openLocalLogFiles',
  'linuxSearchAssistant:reloadLocalLogFile',
  'validation:start',
  'validation:cancel',
  'export:configuration',
  'window:findInPage',
  'window:stopFindInPage',
] as const

export type AllowedIpcChannel = (typeof ALLOWED_IPC_CHANNELS)[number]

export const ALLOWED_IPC_CHANNEL_SET = new Set<string>(ALLOWED_IPC_CHANNELS)

export function assertAllowedChannel(channel: string): asserts channel is AllowedIpcChannel {
  if (!ALLOWED_IPC_CHANNEL_SET.has(channel)) {
    throw new Error(`Forbidden IPC channel: ${channel}`)
  }
}

/** Renderer-safe progress events (main → renderer, not invoke) */
export const ALLOWED_IPC_EVENTS = new Set([
  'validation:progress',
  'scheduler:updated',
  'window:foundInPage',
  'linuxSearchAssistant:sessionExpired',
  'linuxSearchAssistant:connectRequired',
  'linuxSearchAssistant:consoleLog',
])
